// Generated by psc version 0.6.8
var PS = PS || {};
PS.Graphics_UI = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Graphics_UI_Color_Name = PS.Graphics_UI_Color_Name;
    var Graphics_UI_Color_RGB = PS.Graphics_UI_Color_RGB;
    
    /**
     *  | We can make some text.
     */
    var Text = function (text) {
        this.text = text;
    };
    
    /**
     *  | We can make some text.
     */
    var text = function (dict) {
        return dict.text;
    };
    return {
        Text: Text, 
        text: text
    };
})();
var PS = PS || {};
PS.Examples_Graphics_UI_Hello = (function () {
    "use strict";
    var Graphics_UI = PS.Graphics_UI;
    var Prelude = PS.Prelude;
    var hello = function (__dict_Text_103) {
        return Graphics_UI.text(__dict_Text_103)("Hello World");
    };
    return {
        hello: hello
    };
})();
var PS = PS || {};
PS.Graphics_UI_Interpreter_HTML = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Graphics_UI_Color = PS.Graphics_UI_Color;
    var Graphics_UI = PS.Graphics_UI;
    var Debug_Trace = PS.Debug_Trace;
    var Data_Foldable = PS.Data_Foldable;
    var Data_Maybe = PS.Data_Maybe;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var Graphics_UI_Color_RGB = PS.Graphics_UI_Color_RGB;
    var Data_Monoid = PS.Data_Monoid;
    var Data_Array = PS.Data_Array;
    
    /**
     *  This isn't valid html.
     */
    var Text = (function () {
        function Text(value0) {
            this.value0 = value0;
        };
        Text.create = function (value0) {
            return new Text(value0);
        };
        return Text;
    })();
    var textBodyTag = new Graphics_UI.Text(Text.create);
    return {
        Text: Text, 
        textBodyTag: textBodyTag
    };
})();
var PS = PS || {};
PS.Examples_Graphics_UI_Hello_BodyTag = (function () {
    "use strict";
    var Examples_Graphics_UI_Hello = PS.Examples_Graphics_UI_Hello;
    var Prelude = PS.Prelude;
    var Graphics_UI_Interpreter_HTML = PS.Graphics_UI_Interpreter_HTML;
    var greeting = Examples_Graphics_UI_Hello.hello(Graphics_UI_Interpreter_HTML.textBodyTag);
    return {
        greeting: greeting
    };
})();

